---
- hosts: localhost
  connection: local
  
  vars_files:
    - group_vars/aws/default.yml

  vars:
    this_instance_type: "{{ instance_type | default(ec2.instance_type,true)}}"
    this_name_prefix: "{{ instance_name_prefix | default(ec2.instance_name_prefix,true) }}"
    instance_name: "{{ this_name_prefix + '-' + this_instance_type }}"


  roles:
    - role: "{{ playbook_dir }}/roles/aws/iam/user/creds"
    - role: "{{ playbook_dir }}/roles/aws/iam/user/create"
      when: access_key == '' or secret_key == ''
    - role: "{{ playbook_dir }}/roles/aws/vpc/read"
    - role: "{{ playbook_dir }}/roles/aws/vpc/create"
      when: vpc_id == '' or subnet_ids == ''
    - role: "{{ playbook_dir }}/roles/aws/kms_key"
    - role: "{{ playbook_dir }}/roles/aws/ec2/group"
    - role: "{{ playbook_dir }}/roles/aws/ec2/start"
