---
- name: Get VPC information
  amazon.aws.ec2_vpc_net_info:
    access_key: "{{ access_key }}"
    secret_key: "{{ secret_key }}"
    region: "{{ region }}"
    filters:
      tag:Name: "{{ vpc.name }}"
  register: vpc_info

- name: Get Subnet information
  amazon.aws.ec2_vpc_subnet_info:
    access_key: "{{ access_key }}"
    secret_key: "{{ secret_key }}"
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
  register: subnet_info

- name: Set VPC and Subnet IDs as facts
  set_fact:
    vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
    subnet_ids: "{{ subnet_info.subnets | map(attribute='subnet_id') | list }}"

- name: Display VPC and Subnet IDs
  debug:
    msg: "VPC ID: {{ vpc_id }}, Subnet IDs: {{ subnet_ids }}"
